name: Create Pull Request

on:
  push:
    branches:
      - '[a-zA-Z]*/[0-9]*'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '${{ github.ref_name_split[0] }} - ${{ formatDateTime(now(), ''yyyy-MM-dd'') }}'
          branch: 'main'

